### ISSUE TITLE
action scores are sometimes empty but still highlighted

### ISSUE THREAD

**Issue by WestleyArgentum** [WestleyArgentum/influence-game#10]
![screen shot 2015-03-05 at 5 12 02 pm](https://cloud.githubusercontent.com/assets/1900307/6518423/e1ac311e-c35a-11e4-8bb9-cb7c9f319b28.png)

**Comment by sarahghp** [comment]
It is happening on negative scores because right now the highlight is applied by this CSS:

``` css
.team-score-inline {
 [...]
 &[data-score='0']{
    opacity: .15;
  }
}
```

We could fix it by adding a class in JS instead but let me see if there is a smart way to do this in the CSS.
